[package]
name = "rsa"
version = "0.1.0"
authors = ["j-hira <jun1513910@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
rand = "0.7"
rug = "1.7.0"
